### idea get showall
GET http://localhost:4000/api/idea HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY0MTA3MDFiLWUyZDQtNDk5My04ODJlLWNlZjI0MDZkNjBlOCIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NTQzNzEwMjgsImV4cCI6MTU1NDk3NTgyOH0.a0rNHmhO_RkAZRjb8R-osQKmOXn3rWOjzhyete1j-q8

### idea post create
POST http://localhost:4000/api/idea HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY0MTA3MDFiLWUyZDQtNDk5My04ODJlLWNlZjI0MDZkNjBlOCIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NTQzNzEwMjgsImV4cCI6MTU1NDk3NTgyOH0.a0rNHmhO_RkAZRjb8R-osQKmOXn3rWOjzhyete1j-q8
content-type: application/x-www-form-urlencoded

idea=idea_test_1
&description=description_test

### idea get id read
GET http://localhost:4000/api/idea/2894522d-a3f6-44b3-b303-61d1ed5951b2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY0MTA3MDFiLWUyZDQtNDk5My04ODJlLWNlZjI0MDZkNjBlOCIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NTQzNzEwMjgsImV4cCI6MTU1NDk3NTgyOH0.a0rNHmhO_RkAZRjb8R-osQKmOXn3rWOjzhyete1j-q8

### idea put update
PUt http://localhost:4000/api/idea/2894522d-a3f6-44b3-b303-61d1ed5951b2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY0MTA3MDFiLWUyZDQtNDk5My04ODJlLWNlZjI0MDZkNjBlOCIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NTQzNzEwMjgsImV4cCI6MTU1NDk3NTgyOH0.a0rNHmhO_RkAZRjb8R-osQKmOXn3rWOjzhyete1j-q8
Content-Type: application/x-www-form-urlencoded

idea=idea_test_put1

### idea delete remove
DELETE http://localhost:4000/api/idea/2894522d-a3f6-44b3-b303-61d1ed5951b2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY0MTA3MDFiLWUyZDQtNDk5My04ODJlLWNlZjI0MDZkNjBlOCIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NTQzNzEwMjgsImV4cCI6MTU1NDk3NTgyOH0.a0rNHmhO_RkAZRjb8R-osQKmOXn3rWOjzhyete1j-q8

### user showall
GET http://localhost:4000/api/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY0MTA3MDFiLWUyZDQtNDk5My04ODJlLWNlZjI0MDZkNjBlOCIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NTQzNzEwMjgsImV4cCI6MTU1NDk3NTgyOH0.a0rNHmhO_RkAZRjb8R-osQKmOXn3rWOjzhyete1j-q8

### user register
POST http://localhost:4000/register HTtP/1.1
Content-Type: application/x-www-form-urlencoded

username=username
&password=password

### user login
POST http://localhost:4000/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username=username
&password=password

### idea post upvote
POST http://localhost:4000/api/idea/2894522d-a3f6-44b3-b303-61d1ed5951b2/upvote HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY0MTA3MDFiLWUyZDQtNDk5My04ODJlLWNlZjI0MDZkNjBlOCIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NTQzNzEwMjgsImV4cCI6MTU1NDk3NTgyOH0.a0rNHmhO_RkAZRjb8R-osQKmOXn3rWOjzhyete1j-q8

### idea post downvote
POST http://localhost:4000/api/idea/2894522d-a3f6-44b3-b303-61d1ed5951b2/downvote HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY0MTA3MDFiLWUyZDQtNDk5My04ODJlLWNlZjI0MDZkNjBlOCIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NTQzNzEwMjgsImV4cCI6MTU1NDk3NTgyOH0.a0rNHmhO_RkAZRjb8R-osQKmOXn3rWOjzhyete1j-q8

### idea post bookmark
POST http://localhost:4000/api/idea/2894522d-a3f6-44b3-b303-61d1ed5951b2/bookmark HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY0MTA3MDFiLWUyZDQtNDk5My04ODJlLWNlZjI0MDZkNjBlOCIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NTQzNzEwMjgsImV4cCI6MTU1NDk3NTgyOH0.a0rNHmhO_RkAZRjb8R-osQKmOXn3rWOjzhyete1j-q8

### idea delete bookmark
DELETE http://localhost:4000/api/idea/2894522d-a3f6-44b3-b303-61d1ed5951b2/bookmark HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY0MTA3MDFiLWUyZDQtNDk5My04ODJlLWNlZjI0MDZkNjBlOCIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NTQzNzEwMjgsImV4cCI6MTU1NDk3NTgyOH0.a0rNHmhO_RkAZRjb8R-osQKmOXn3rWOjzhyete1j-q8

### comment showCommentsByIdea
GET http://localhost:4000/api/comment/idea/2894522d-a3f6-44b3-b303-61d1ed5951b2 HTTP/1.1

### comment showCommentsByUser
GET http://localhost:4000/api/comment/user/f410701b-e2d4-4993-882e-cef2406d60e8 HTTP/1.1

### comment createComment
POST http://localhost:4000/api/comment/idea/2894522d-a3f6-44b3-b303-61d1ed5951b2 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY0MTA3MDFiLWUyZDQtNDk5My04ODJlLWNlZjI0MDZkNjBlOCIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NTQzNzEwMjgsImV4cCI6MTU1NDk3NTgyOH0.a0rNHmhO_RkAZRjb8R-osQKmOXn3rWOjzhyete1j-q8

comment=this_is_a_comment_3

### comment showone comment
GET http://localhost:4000/api/comment/a58efb7d-6b83-4d14-9baf-430f7597838a HTTP/1.1

### comment remove comment
DELETE http://localhost:4000/api/comment/f1d63929-5018-459e-a1c6-5f363193f553 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY0MTA3MDFiLWUyZDQtNDk5My04ODJlLWNlZjI0MDZkNjBlOCIsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE1NTQzNzEwMjgsImV4cCI6MTU1NDk3NTgyOH0.a0rNHmhO_RkAZRjb8R-osQKmOXn3rWOjzhyete1j-q8
